<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exception Handling in C++</title>

    <link rel="alternate" href="https://campusempresa.com/mod/cplusplus/exception-handling" hreflang="es" />
	<link rel="alternate" href="https://campusempresa.cat/mod/cplusplus/exception-handling" hreflang="ca" />
	<link rel="alternate" href="https://enterprisecampus.net/mod/cplusplus/exception-handling" hreflang="en" />
    
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
	<link href="/css/site.css" rel="stylesheet">
	
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  	<script type="text/javascript" src="js/math_init.js"></script>
  	<script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js"></script>
  	<script type="text/javascript" src="/js/cookie.js"></script>
  	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body>
    <div id="content">
		<div id="header" class="container-xxl">
	<div class="row">
		<div class="col-8 p-0">
			<h1 class="m-0 p-0">
				<a href="/"><img src="/img/logo_header.png" style="visibility:hiddenxx;"></a>
			</h1>
		</div>
		<div class="col-4 p-0 text-end">
			<h2 id="main_title"><cite>Building today's and tomorrow's society</cite></h2>
			<h3 id="main_subtitle"></h3>
		</div>
	</div>
</div>
<div class="container-xxl" style="margin-top: -1em;">
	<div class="row">
		<div class="col-12 p-0 m-0 text-end">
													<b id="lit_lang_es" class="px-2">EN</b>
				|
				<a href="https://campusempresa.com/mod/cplusplus/exception-handling" class="px-2">ES</a></b>
				|
				<a href="https://campusempresa.cat/mod/cplusplus/exception-handling" class="px-2">CA</a>
					</div>
	</div>
</div>
   <div class="top-bar container-fluid">
	<div class="container-xxl">
		<div class="row">
			<div class="col" id="left_menu">
				<a href="/objective">The Project</a>
				<a href="/about">About Us</a>
				<a href="/contribute">Contribute</a>
				<a href="/donate">Donations</a>
				<a href="/licence">License</a>
			</div>
		</div>
	</div>
   </div>

<div class="container-xxl" id="main_content">
	<div class="row">
		<div class="col-12 col-lg-8">
			<div id="nav1" class="navigation"></div>
			<div id="inner_content"><div class='row navigation'>
	<div class='col-4'>
					<a href='templates'>&#x25C4;Templates</a>
			</div>
	<div class='col-4 text-center'>
		<a href="./" class="title">Exception Handling in C++</a>
	</div>
	<div class='col-4 text-end'>
					<a href='file-io'>File I/O &#x25BA;</a>
			</div>
</div>
<div class='content'></div><h1>Introduction to Exception Handling</h1>
<div class='content'><p>Exception handling is a crucial aspect of robust software development. It allows a program to deal with unexpected situations (exceptions) gracefully, rather than crashing or producing incorrect results.</p>
</div><h2>Key Concepts</h2>
<div class='content'><ul>
<li><strong>Exception</strong>: An event that disrupts the normal flow of the program.</li>
<li><strong>Try Block</strong>: A block of code that is tested for exceptions.</li>
<li><strong>Catch Block</strong>: A block of code that handles the exception.</li>
<li><strong>Throw Statement</strong>: Used to signal the occurrence of an exception.</li>
</ul>
</div><h1>Basic Exception Handling</h1>
<div class='content'></div><h2>Try and Catch Blocks</h2>
<div class='content'><p>In C++, exceptions are handled using <code>try</code> and <code>catch</code> blocks. The <code>try</code> block contains the code that might throw an exception, and the <code>catch</code> block contains the code to handle the exception.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKaW50IG1haW4oKSB7CiAgICB0cnkgewogICAgICAgIGludCBudW0xID0gMTA7CiAgICAgICAgaW50IG51bTIgPSAwOwogICAgICAgIGlmIChudW0yID09IDApIHsKICAgICAgICAgICAgdGhyb3cgIkRpdmlzaW9uIGJ5IHplcm8gZXJyb3IhIjsKICAgICAgICB9CiAgICAgICAgY291dCA8PCBudW0xIC8gbnVtMiA8PCBlbmRsOwogICAgfSBjYXRjaCAoY29uc3QgY2hhciogZSkgewogICAgICAgIGNvdXQgPDwgIkV4Y2VwdGlvbjogIiA8PCBlIDw8IGVuZGw7CiAgICB9CiAgICByZXR1cm4gMDsKfQ=="))));alert("Copied!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
using namespace std;

int main() {
    try {
        int num1 = 10;
        int num2 = 0;
        if (num2 == 0) {
            throw &quot;Division by zero error!&quot;;
        }
        cout &lt;&lt; num1 / num2 &lt;&lt; endl;
    } catch (const char* e) {
        cout &lt;&lt; &quot;Exception: &quot; &lt;&lt; e &lt;&lt; endl;
    }
    return 0;
}</pre></div><div class='content'><p>In this example:</p>
<ul>
<li>The <code>try</code> block contains code that might throw an exception.</li>
<li>The <code>throw</code> statement throws an exception if <code>num2</code> is zero.</li>
<li>The <code>catch</code> block catches the exception and handles it by printing an error message.</li>
</ul>
</div><h1>Throwing Exceptions</h1>
<div class='content'><p>You can throw exceptions of any type, including built-in types and user-defined types.</p>
</div><h2>Throwing Built-in Types</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKaW50IG1haW4oKSB7CiAgICB0cnkgewogICAgICAgIHRocm93IDQwNDsKICAgIH0gY2F0Y2ggKGludCBlKSB7CiAgICAgICAgY291dCA8PCAiRXhjZXB0aW9uOiBFcnJvciBjb2RlICIgPDwgZSA8PCBlbmRsOwogICAgfQogICAgcmV0dXJuIDA7Cn0="))));alert("Copied!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
using namespace std;

int main() {
    try {
        throw 404;
    } catch (int e) {
        cout &lt;&lt; &quot;Exception: Error code &quot; &lt;&lt; e &lt;&lt; endl;
    }
    return 0;
}</pre></div><h2>Throwing User-defined Types</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKY2xhc3MgTXlFeGNlcHRpb24gewpwdWJsaWM6CiAgICBjb25zdCBjaGFyKiB3aGF0KCkgY29uc3QgewogICAgICAgIHJldHVybiAiQ3VzdG9tIGV4Y2VwdGlvbiBvY2N1cnJlZCEiOwogICAgfQp9OwoKaW50IG1haW4oKSB7CiAgICB0cnkgewogICAgICAgIHRocm93IE15RXhjZXB0aW9uKCk7CiAgICB9IGNhdGNoIChNeUV4Y2VwdGlvbiYgZSkgewogICAgICAgIGNvdXQgPDwgIkV4Y2VwdGlvbjogIiA8PCBlLndoYXQoKSA8PCBlbmRsOwogICAgfQogICAgcmV0dXJuIDA7Cn0="))));alert("Copied!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
using namespace std;

class MyException {
public:
    const char* what() const {
        return &quot;Custom exception occurred!&quot;;
    }
};

int main() {
    try {
        throw MyException();
    } catch (MyException&amp; e) {
        cout &lt;&lt; &quot;Exception: &quot; &lt;&lt; e.what() &lt;&lt; endl;
    }
    return 0;
}</pre></div><div class='content'></div><h1>Multiple Catch Blocks</h1>
<div class='content'><p>You can have multiple <code>catch</code> blocks to handle different types of exceptions.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKaW50IG1haW4oKSB7CiAgICB0cnkgewogICAgICAgIHRocm93IDMuMTQ7CiAgICB9IGNhdGNoIChpbnQgZSkgewogICAgICAgIGNvdXQgPDwgIkNhdWdodCBhbiBpbnRlZ2VyOiAiIDw8IGUgPDwgZW5kbDsKICAgIH0gY2F0Y2ggKGRvdWJsZSBlKSB7CiAgICAgICAgY291dCA8PCAiQ2F1Z2h0IGEgZG91YmxlOiAiIDw8IGUgPDwgZW5kbDsKICAgIH0gY2F0Y2ggKC4uLikgewogICAgICAgIGNvdXQgPDwgIkNhdWdodCBhbiB1bmtub3duIGV4Y2VwdGlvbi4iIDw8IGVuZGw7CiAgICB9CiAgICByZXR1cm4gMDsKfQ=="))));alert("Copied!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
using namespace std;

int main() {
    try {
        throw 3.14;
    } catch (int e) {
        cout &lt;&lt; &quot;Caught an integer: &quot; &lt;&lt; e &lt;&lt; endl;
    } catch (double e) {
        cout &lt;&lt; &quot;Caught a double: &quot; &lt;&lt; e &lt;&lt; endl;
    } catch (...) {
        cout &lt;&lt; &quot;Caught an unknown exception.&quot; &lt;&lt; endl;
    }
    return 0;
}</pre></div><div class='content'><p>In this example:</p>
<ul>
<li>The <code>catch</code> blocks handle different types of exceptions.</li>
<li>The <code>catch(...)</code> block is a catch-all handler for any type of exception not caught by previous handlers.</li>
</ul>
</div><h1>Standard Exception Classes</h1>
<div class='content'><p>C++ provides a set of standard exception classes defined in the <code>&lt;stdexcept&gt;</code> header.</p>
</div><h2>Common Standard Exceptions</h2>
<div class='content'><p>| Exception Class | Description |
|-----------------|-------------|
| <code>std::exception</code> | Base class for all standard exceptions |
| <code>std::runtime_error</code> | Represents runtime errors |
| <code>std::logic_error</code> | Represents logical errors |
| <code>std::out_of_range</code> | Thrown when an out-of-range error occurs |
| <code>std::invalid_argument</code> | Thrown when an invalid argument is passed |</p>
</div><h2>Using Standard Exceptions</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgojaW5jbHVkZSA8c3RkZXhjZXB0Pgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKaW50IG1haW4oKSB7CiAgICB0cnkgewogICAgICAgIHRocm93IHJ1bnRpbWVfZXJyb3IoIlJ1bnRpbWUgZXJyb3Igb2NjdXJyZWQiKTsKICAgIH0gY2F0Y2ggKHJ1bnRpbWVfZXJyb3ImIGUpIHsKICAgICAgICBjb3V0IDw8ICJFeGNlcHRpb246ICIgPDwgZS53aGF0KCkgPDwgZW5kbDsKICAgIH0KICAgIHJldHVybiAwOwp9"))));alert("Copied!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
#include &lt;stdexcept&gt;
using namespace std;

int main() {
    try {
        throw runtime_error(&quot;Runtime error occurred&quot;);
    } catch (runtime_error&amp; e) {
        cout &lt;&lt; &quot;Exception: &quot; &lt;&lt; e.what() &lt;&lt; endl;
    }
    return 0;
}</pre></div><div class='content'></div><h1>Advanced Exception Handling</h1>
<div class='content'></div><h2>Custom Exception Classes</h2>
<div class='content'><p>You can create your own exception classes by inheriting from <code>std::exception</code>.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgojaW5jbHVkZSA8ZXhjZXB0aW9uPgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKY2xhc3MgTXlFeGNlcHRpb24gOiBwdWJsaWMgZXhjZXB0aW9uIHsKcHVibGljOgogICAgY29uc3QgY2hhciogd2hhdCgpIGNvbnN0IG5vZXhjZXB0IG92ZXJyaWRlIHsKICAgICAgICByZXR1cm4gIk15IGN1c3RvbSBleGNlcHRpb24iOwogICAgfQp9OwoKaW50IG1haW4oKSB7CiAgICB0cnkgewogICAgICAgIHRocm93IE15RXhjZXB0aW9uKCk7CiAgICB9IGNhdGNoIChNeUV4Y2VwdGlvbiYgZSkgewogICAgICAgIGNvdXQgPDwgIkV4Y2VwdGlvbjogIiA8PCBlLndoYXQoKSA8PCBlbmRsOwogICAgfQogICAgcmV0dXJuIDA7Cn0="))));alert("Copied!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
#include &lt;exception&gt;
using namespace std;

class MyException : public exception {
public:
    const char* what() const noexcept override {
        return &quot;My custom exception&quot;;
    }
};

int main() {
    try {
        throw MyException();
    } catch (MyException&amp; e) {
        cout &lt;&lt; &quot;Exception: &quot; &lt;&lt; e.what() &lt;&lt; endl;
    }
    return 0;
}</pre></div><div class='content'></div><h2>Exception Specifications (Deprecated)</h2>
<div class='content'><p>Exception specifications were used to specify which exceptions a function might throw, but they are deprecated in C++11 and removed in C++17.</p>
</div><h2>noexcept Specifier</h2>
<div class='content'><p>The <code>noexcept</code> specifier indicates that a function does not throw any exceptions.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKdm9pZCBzYWZlRnVuY3Rpb24oKSBub2V4Y2VwdCB7CiAgICBjb3V0IDw8ICJUaGlzIGZ1bmN0aW9uIGlzIGd1YXJhbnRlZWQgbm90IHRvIHRocm93IGV4Y2VwdGlvbnMuIiA8PCBlbmRsOwp9CgppbnQgbWFpbigpIHsKICAgIHNhZmVGdW5jdGlvbigpOwogICAgcmV0dXJuIDA7Cn0="))));alert("Copied!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
using namespace std;

void safeFunction() noexcept {
    cout &lt;&lt; &quot;This function is guaranteed not to throw exceptions.&quot; &lt;&lt; endl;
}

int main() {
    safeFunction();
    return 0;
}</pre></div><div class='content'></div><h1>Conclusion</h1>
<div class='content'><p>Exception handling in C++ is a powerful feature that helps create robust and error-resistant programs. By using <code>try</code>, <code>catch</code>, and <code>throw</code>, you can manage errors gracefully. Understanding standard exception classes and creating custom exceptions further enhances your ability to handle errors effectively. Remember to use the <code>noexcept</code> specifier for functions that are guaranteed not to throw exceptions, improving code reliability and performance.</p>
</div><div class='row navigation'>
	<div class='col-4'>
					<a href='templates'>&#x25C4;Templates</a>
			</div>
	<div class='col-4 text-center'>
		<a href="./" class="title">Exception Handling in C++</a>
	</div>
	<div class='col-4 text-end'>
					<a href='file-io'>File I/O &#x25BA;</a>
			</div>
</div>
</div>
		</div>
		<div class="col-12 col-lg-4 publi" id="div_publi">
			<h1>Advertising</h1>
			<p>This space is reserved for advertising.</p>
			<p>If you want to be a sponsor, contact us to include links in this area: <a href='mailto:admin@campusempresa.cat'>admin@campusempresa.cat</a></p>
			<p>Thank you for collaborating!</p>
		</div>
	</div>
</div>

   <div class="container-xxl my-3">
	<div class="row">
		<div class="col">
			<footer>&copy; Copyright 2024. All rights reserved</footer>
		</div>
	</div>
</div>	

<div id="cookies_adv" style="display:none;">
	Fem servir galetes per millorar la teva experiència d'ús i oferir continguts adaptats als teus interessos
    <a href="#" id="btn_accept_cookies" class="button">Accept</a>
    <a href="/cookies">More Information</a>
</div>	

	</div>    
</body>
</html>
